name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # O tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd my-app  # Cambia al directorio donde está el Dockerfile
          docker build -t lssalas/hello-world-app:latest .  # Construir la imagen
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push lssalas/hello-world-app:latest  # Empujar la imagen a Docker Hub
